### ISSUE TITLE
Why owner key is needed?

### ISSUE THREAD

**Issue by abitmore** [bitshares/stakeBTS#1]
Mentioned in README:
> NOTICE: UPTICK is a must to operate bot properly. Account that you wish to use for the bot must be imported with all 3 private keys (Owner, Active and Memo) into the uptick. On BOT start you will be asked to enter WALLET password from the uptick.

I don't think the owner private key is necessary.

**Comment by litepresence** [comment]
I'm not sure that it is needed either and I questioned it myself.   That was part of the legacy README.md from iamredbar.   Perhaps he had some reasoning?   I'm not sure.   I can't see how this would not function with just Active and Memo.

**Comment by litepresence** [comment]
I slept on this and also had discussion w/ @christophersanborn 

Agreed, no need for owner key on this script.   Nice catch.   Will update README.md

**Comment by litepresence** [comment]
https://github.com/bitshares/stakeBTS/commit/dba9eb35fde02aa45560f718cde1ddd0217edfcc
